#此文件为Nginx服务器伪静态规则，不清楚怎么写的情况下请不要更改内容和文件名称
#Nginx服务器伪静态请将该文件内容粘贴到伪静态配置中，不会可咨询机房技术协助操作
#如果是宝塔-Nginx套装搭建的 请在网站列表 点击设置->伪静态，将本文件内容粘贴过去保存即可生效

#文章插件伪静态
location  /article/ { 
 rewrite ^/article/(\d+).html /article/index.php?id=$1 last;
 rewrite ^/article/index.html /article/index.php last;
} 

#网站首页伪静态
location  / { 
 rewrite ^/classList/(\d+).html(.*?) /index.php?act=classList&cid=$1 last;
 rewrite ^/detail/(\d+).html(.*?) /index.php?act=detail&tid=$1 last;
 rewrite ^/act/([\w\-]+).html(.*?) /index.php?act=$1 last;
 rewrite ^/index.html(.*?) /index.php last;
}
